# Task 24: Data Type Cleaning

## Internship: AI & ML Track – VEDA

### Objective
Identify incorrect data types in a dataset and convert columns to appropriate data types using Pandas.

### Description
Data type cleaning is the process of identifying and correcting inappropriate data types in a dataset to ensure accurate data analysis and machine learning.

### Tools Used
- Python
- Pandas
- Jupyter Notebook

### Dataset
Employee Dataset

### Deliverables
- Original data types
- Corrected data types
- Explanation of data type conversions

### Learning Outcome
Learned how to inspect data types using `dtypes`, convert columns using `pd.to_numeric()` and `pd.to_datetime()`, and verify the cleaned dataset.

In [1]:
import pandas as pd

In [2]:
data = {
    "Employee_ID": ["101", "102", "103", "104", "105"],
    "Name": ["Arun", "Priya", "Kumar", "Divya", "Ravi"],
    "Age": ["25", "30", "28", "35", "27"],
    "Salary": ["25000", "35000", "30000", "45000", "28000"],
    "Joining_Date": [
        "2024-01-15",
        "2023-06-20",
        "2024-03-10",
        "2022-11-05",
        "2023-09-18"
    ]
}

df = pd.DataFrame(data)

df

  Employee_ID   Name Age Salary Joining_Date
0         101   Arun  25  25000   2024-01-15
1         102  Priya  30  35000   2023-06-20
2         103  Kumar  28  30000   2024-03-10
3         104  Divya  35  45000   2022-11-05
4         105   Ravi  27  28000   2023-09-18

In [3]:
print("Original Data Types:")
print(df.dtypes)

Original Data Types:
Employee_ID     str
Name            str
Age             str
Salary          str
Joining_Date    str
dtype: object

In [4]:
df["Age"] = pd.to_numeric(df["Age"])
df["Salary"] = pd.to_numeric(df["Salary"])
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

print("Data types after conversion:")
print(df.dtypes)

Data types after conversion:
Employee_ID                str
Name                       str
Age                      int64
Salary                   int64
Joining_Date    datetime64[us]
dtype: object

In [5]:
print("Cleaned Dataset:")
display(df)

print("\nFinal Data Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

Cleaned Dataset:

  Employee_ID   Name  Age  Salary Joining_Date
0         101   Arun   25   25000   2024-01-15
1         102  Priya   30   35000   2023-06-20
2         103  Kumar   28   30000   2024-03-10
3         104  Divya   35   45000   2022-11-05
4         105   Ravi   27   28000   2023-09-18

Final Data Types:
Employee_ID                str
Name                       str
Age                      int64
Salary                   int64
Joining_Date    datetime64[us]
dtype: object

Missing Values:
Employee_ID     0
Name            0
Age             0
Salary          0
Joining_Date    0
dtype: int64

In [6]:
comparison = pd.DataFrame({
    "Original Data Type": pd.DataFrame(data).dtypes,
    "Corrected Data Type": df.dtypes
})

comparison

             Original Data Type Corrected Data Type
Employee_ID                 str                 str
Name                        str                 str
Age                         str               int64
Salary                      str               int64
Joining_Date                str      datetime64[us]

In [7]:
print("Average Age:", df["Age"].mean())
print("Average Salary:", df["Salary"].mean())

print("\nEmployees who earn more than 30000:")
display(df[df["Salary"] > 30000])

Average Age: 29.0
Average Salary: 32600.0

Employees who earn more than 30000:

  Employee_ID   Name  Age  Salary Joining_Date
1         102  Priya   30   35000   2023-06-20
3         104  Divya   35   45000   2022-11-05

### Conclusion

In Task 24, I identified incorrect data types in an employee dataset and converted Age and Salary into numeric types and Joining_Date into datetime format using Pandas. I verified the corrected data types and checked for missing values. This task demonstrates how proper data types improve data analysis and machine learning data preparation.